services:
  prestart:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    build: 
      context: ./backend
    networks:
      - app_network
    command: bash scripts/prestart.sh
    env_file:
      - .env

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    container_name: venture-validator-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    #depends_on:
    #  ollama:
    #    condition: service_healthy
    #  prestart:
    #    condition: service_completed_successfully
    networks:
      - app_network
    env_file:
      - .env

  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - 11434:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app_network

  frontend:
    container_name: venture-validator-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app_network
    
networks:
  app_network:
    driver: bridge

volumes:
  ollama_data:
    driver: local